# Numpy For Matrix
## 矩阵的逆，秩，转置
## 矩阵的行列式值（方阵）
## 矩阵的特征值与特征向量求法
## 矩阵的迹

### 约定矩阵用A,B,C..Z表示，数组向量用a,b,c...z表示

In [1]:
defaultdir=dir()
len(defaultdir)

22

In [2]:
from numpy import * #import all metholds of numpy

In [3]:
Numpydir=dir()
len(Numpydir)

605

In [4]:
NumObjectsOfNumpy=605-22
NumObjectsOfNumpy

583

In [5]:
import numpy as np # call numpy function with np. if needed

In [6]:
a=array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
A=mat(a)

In [8]:
A

matrix([[1, 2, 3]])

In [9]:
shape(A)

(1, 3)

In [10]:
shape(a)

(3,)

In [11]:
B=matrix([[1,2,3],[4,5,6]])

In [12]:
shape(B)

(2, 3)

In [13]:
b=array([[1,2,3],[4,5,6]])

In [14]:
shape(b)

(2, 3)

In [15]:
c=array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [16]:
shape(c)

(2, 2, 3)

In [17]:
d=array([[1],[2],[3]])
shape(d)

(3, 1)

###  通过下标，获取多维数组的值和矩阵的值，方式不同

In [18]:
c[0][1][2]

6

In [19]:
B[1,2]

6

### Matrix 都是二维的，数组可以有3，4，5，...N维

In [20]:
C=mat(zeros((4,4)))
C

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
D=mat(ones((3,4)))
D

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## 生成单位阵

In [22]:
E=eye(3,3,dtype=int)

In [23]:
E

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
F=eye(4,3,dtype=float)
F

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [25]:
F=eye(4,4,k=1,dtype=float)
F

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [26]:
F=eye(4,4,k=-1,dtype=float)
F

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## 副对角线（右上左下）

In [27]:
a=[1,2,3,4]
G=diag(a,0)
G

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
H=fliplr(G)
H

array([[0, 0, 0, 1],
       [0, 0, 2, 0],
       [0, 3, 0, 0],
       [4, 0, 0, 0]])

In [29]:
I=diag(a,1)
I

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [30]:
J=diag(a,-1)
J

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## 逆时针旋转90度

In [31]:
K=rot90(G)
K

array([[0, 0, 0, 4],
       [0, 0, 3, 0],
       [0, 2, 0, 0],
       [1, 0, 0, 0]])

## 旋转3次，相当于顺时针转90度

In [32]:
L=rot90(G,3)
L

array([[0, 0, 0, 1],
       [0, 0, 2, 0],
       [0, 3, 0, 0],
       [4, 0, 0, 0]])

### 矩阵求逆

In [33]:
M=mat(random.randint(-10,10,(3,3)))

In [34]:
M

matrix([[-9, -3,  2],
        [-5, -7, -4],
        [-6, -1, -6]])

In [35]:
M.I

matrix([[-0.09547739,  0.05025126, -0.06532663],
        [ 0.01507538, -0.16582915,  0.11557789],
        [ 0.09296482, -0.02261307, -0.12060302]])

In [36]:
M*M.I

matrix([[ 1.00000000e+00, -2.77555756e-17, -2.77555756e-17],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [-2.77555756e-17, -5.55111512e-17,  1.00000000e+00]])

In [37]:
M.I*M

matrix([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00,  1.11022302e-16],
        [ 2.77555756e-17,  4.16333634e-17,  1.00000000e+00]])

In [38]:
N=mat(random.randint(-10,10,(2,3)))
N

matrix([[ 8, -4,  5],
        [ 7, -5, -5]])

In [39]:
N.I

matrix([[ 0.05581216,  0.04195535],
        [-0.01809084, -0.04118553],
        [ 0.09622787, -0.10007698]])

### 矩阵可逆的充要条件是其行列式不为0，行列式一般都指方阵
### 这儿上面的2\*3矩阵的逆是一个3\*2（伪逆）
- 伪逆参见https://www.cnblogs.com/AndyJee/p/5082508.html

In [40]:
O=mat(array([[2,3],[2,3]]))

行列式的值求法 np.linalg.det(M)

In [41]:
linalg.det(O)

0.0

In [42]:
linalg.det(M)

-398.0

In [43]:
P=N.I

In [44]:
P.I

matrix([[ 8., -4.,  5.],
        [ 7., -5., -5.]])

In [45]:
P.I*P*P.I

matrix([[ 8., -4.,  5.],
        [ 7., -5., -5.]])

In [46]:
P*P.I*P

matrix([[ 0.05581216,  0.04195535],
        [-0.01809084, -0.04118553],
        [ 0.09622787, -0.10007698]])

In [47]:
P

matrix([[ 0.05581216,  0.04195535],
        [-0.01809084, -0.04118553],
        [ 0.09622787, -0.10007698]])

- 转置

In [48]:
N.T

matrix([[ 8,  7],
        [-4, -5],
        [ 5, -5]])

In [49]:
N.H

matrix([[ 8,  7],
        [-4, -5],
        [ 5, -5]])

In [50]:
N.max(0)

matrix([[ 8, -4,  5]])

In [51]:
multiply(N,N)

matrix([[64, 16, 25],
        [49, 25, 25]])

In [52]:
Q=mat(np.arange(1,17).reshape(4,4))

In [53]:
Q

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

- 点乘， 相应元素相乘

In [54]:
multiply(Q,Q)

matrix([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144],
        [169, 196, 225, 256]])

In [55]:
dot(Q,Q)

matrix([[ 90, 100, 110, 120],
        [202, 228, 254, 280],
        [314, 356, 398, 440],
        [426, 484, 542, 600]])

In [56]:
Q*Q

matrix([[ 90, 100, 110, 120],
        [202, 228, 254, 280],
        [314, 356, 398, 440],
        [426, 484, 542, 600]])

## A与B的特征值是否相同是判断A与B是否相似的根本依据
## A~B

- 矩阵特征值一般是指方阵，关于$\lambda$的方程|$\lambda$E-A|=0 的所有根就是A特征值